global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tf-serving-monitor'
    scrape_interval: 5s
    metrics_path: '/monitoring/prometheus/metrics'
    static_configs:
      - targets: ['churn-container:8501']  